### PR TITLE
[RFR]: SelectArrayInput don't translate when optionText is a React Component

### PR DESCRIPTION
**Pull request by tkvw**
The translate option did not check if the optionText is a component. Component clones should not be translated. Added `translate` prop to clone properties.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Why would you add the `translate` prop? It's the component(s responsibility to grab the `translate` prop using the `translate` HOC. Otherwise, you risk that the component doesn't need `translate` and passes it to underlying components, possibly DOM elements, and trigger a warning.

**Comment by tkvw** [comment]
I thought about that, but because it's an `OptionText` with potentially a lot of choices, I thought this would be more efficient. But I'll remove it

**Comment by tkvw** [comment]
Translate prop removed

**Comment by fzaninotto** [comment]
thanks!

**Pull request merged**
