### PR TITLE
Adding a link to the updated Hebrew translations.

### PR DESCRIPTION
**Pull request by motro**
Hi guys,
I've added a more recent translation of AOR & published a NPM package for it (the previous repo didn't have one).

### CODE REVIEW

**Comment by fzaninotto** [comment]
ping @mstmustisnt, is your translation still supported?

**Comment by fzaninotto** [comment]
@motro I'd prefer that you collaborate with @mstmustisnt on the [mstmustisnt/aor-language-hebrew](https://github.com/mstmustisnt/aor-language-hebrew) repository instead of starting a new one.

**Comment by motro** [comment]
@fzaninotto I'd prefer that too, however there was never a NPM package published under this name (meaning no one has used it before since trying to install it would fail) and the repo hasn't been updated for the last 7 months.
In fact, I just published the NPM package yesterday for the first time: [https://www.npmjs.com/package/aor-language-hebrew](https://www.npmjs.com/package/aor-language-hebrew)

**Comment by mstmustisnt** [comment]
Sorry, guys. I'm not able to provide support to keep Hebrew translations updated.

**Pull request merged**
