### PR TITLE
[RFR] Refactor resources handling

### LINKED ISSUE #1445: CustomRoutes refresh does not trigger `declareResources`.
**What you were expecting:**
Refreshing page from a  declared `customRoutes` using F5 and remaining in the same location and context.

**What happened instead:**
App crashes telling me: `Cannot read property 'list' of undefined`

**Steps to reproduce:**
I am not sure how to reproduce the error as I have other `customRoutes` that do not have the same issue

**Related code:**
First, I realized that in most other situations, or if I move the same routes from `customRoutes` to `Resource` just for the intention of testing the App would not crash. The bug seems to be inconsistent.

After logging in `initializeResources(children)` and within the `List` component, it seemed that `this.props.declareResources` was not called before the `List` component was mounted.

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable): N/A
* React version: "16.0.0",
* Browser: Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by djhi**
Fixes #1445

- [x] Refactor resources handling
- [x] Added e2e tests to validate

### CODE REVIEW

**Comment by santaclauze** [comment]
https://github.com/santaclauze/aor-customRoutes-bug

Still have the same problem. There are situations where we would like to pass a component that has been created with your own components List/Create/Edit/Show but in a customeRoutes.

In my example, PostList and UserList are passed to customeRoutes and still return an error:
`Cannot read property 'list' of undefined`.

As stated in my original post, it seems that the resources are set but not yet loaded.

**Comment by djhi** [comment]
No, #1462 targets `master` while #1466 targets `next`. We haven't released this fix yet

**Comment by santaclauze** [comment]
kk ty for the details. Looking forward.

**Comment by kopax** [comment]
I have forked `master` and tagged a version [1.3.2-fixed](https://github.com/kopaxgroup/admin-on-rest/tree/1.3.2-fixed) with `lib` pushed so it can be installed from `npm` : 

I have used this version over the @santaclauze [reproduction](https://github.com/marmelab/admin-on-rest/issues/1445#issuecomment-361818465) with these additionals commands: 

    npm install --save git+https://git@github.com:kopaxgroup/admin-on-rest.git#1.3.2-fixed
    make install
    make run

`customRoutes` aren't rendering at all, Is this supposed to fix #1445 ?

**Comment by fzaninotto** [comment]
1.4.0 has been released today. Can you check if it fixes your issue?

**Comment by santaclauze** [comment]
@fzaninotto unfortunately not. 

The problem seems to be the same, `declareResources` is not called before `customRoutes` is rendered. 

https://github.com/santaclauze/aor-customRoutes-bug-test-2

```
make install
make run
```

then navigate between:

http://localhost:8081/#/posts
and
http://localhost:8081/#/comments

and refresh the pages manually.

I left some logs which seems to suggest that `declareResources` is now called, but only after the rendering of the component which creates the error related to `mapStateToProps` as the data is not yet loaded in the resource that we are trying to display (in this case comments).

test_aor

**Comment by fzaninotto** [comment]
ping @djhi

**Comment by djhi** [comment]
No, they are, see the custom routes pages included in the simple example. The issue here is that their declaration is asynchronous in the simple example but our default CRUD pages (List, Create, Edit, Show and Delete) are not meant to be used inside custom routes.

@fzaninotto: we can make them usable in custom routes quite easily by fixing the `mapStateToProps` for each of them, ensuring the resource is here before trying to read it.

**Comment by fzaninotto** [comment]
Not in 1.0, this is a new feature. 

@santaclauze I suggest you open an enhancement request for using `List`, `Create`, `Edit`, `Show` and `Delete` components in custom routes. We may implement it in version 2.0.

**Comment by afilp** [comment]
@fzaninotto This would be great for 2.0, I also need this functionality. Thanks!

**Comment by kopax** [comment]
> @fzaninotto: we can make them usable in custom routes quite easily by fixing the mapStateToProps for each of them, ensuring the resource is here before trying to read it.

@djhi just as a comment: I believe it would not be the best place to fix it. As people may extend react-admin, it should be done at the application level instead of component level.

**Comment by fzaninotto** [comment]
@kopax if you have an idea of how to fix it properly, please open a PR!

**Comment by kopax** [comment]
@fzaninotto is there a chance to get in touch with you?

**Comment by fzaninotto** [comment]
Sure, you can email me using my first name at my company name, followed by a dot and then by a com.

**Comment by kopax** [comment]
@fzaninotto I've sent you an email

**Comment by fzaninotto** [comment]
@kopax I didn't receive it. I suggest you go to the marmelab.com website and hit the Contact button.

**Comment by kopax** [comment]
@fzaninotto I've forwarded the email to contact@.

**Comment by fzaninotto** [comment]
Still not received. I believe your email wasn't sent.

**Comment by kopax** [comment]
> Not in 1.0, this is a new feature.

@fzaninotto not sure if this is related but I've noticed that it also break the `customApp.md`. See [#1120](https://github.com/marmelab/admin-on-rest/issues/1120) for more details.

If this is also 1.0 issues, should it be fixed in 1.0 ?

**Pull request merged**
