### PR TITLE
make auto complete possible to store inital values

### PR DESCRIPTION
**Pull request by vedmalex**
this make possible to setup initial value from list of choises in case when chioces are loaded in async way.
otherwise we see empty values, because it is chosen from empty initial load.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Any new feature must be PRed against the `next` branch. Also, please add a unit test.

**Comment by djhi** [comment]
@vedmalex Any news on this one ?

**Comment by vedmalex** [comment]
@djhi not yet... sorry... i've make local copy of files... and have relax :) i have more files to see but now too busy with current tasks

**Comment by djhi** [comment]
Superseded by #1340

**Pull request closed without merging**
