### PR TITLE
[RFR] Datagrid style

### PR DESCRIPTION
**Pull request by tkvw**
Allow stylesheets to override column style per resource and add a static width to select column in datagrid.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Lacks documentation.

Also, I had forgotten about the ability to override styles using plain CSS. In other terms, it's not tested, and it may break in various other places.

**Comment by tkvw** [comment]
Not sure what you're expecting from me? Should I add docs, or don't you want to support external css anymore?

**Comment by fzaninotto** [comment]
What does your change allow that a user can't do with `withStyles`?

If you're adding a way to override the styles of a cell with CSS instead of JSS, you must explain it in the `Theming` and `List` documentation.

**Comment by fzaninotto** [comment]
bump

**Comment by tkvw** [comment]
I can add docs for this, but only if you want to support custom styling through external css. I've thought about it a bit more and think your comment about `withStyles` makes sense. This is just a dirty quick way of applying style. So let me know what to do or you can close this topic.

**Comment by fzaninotto** [comment]
Somehow related to #1694, I think we should use only one style customization path, and that should be `withStyles`. But, to allow developers to override inner components, we should pass specific fields of the `classes` prop to children component. 

Anyway, that invalidates the plain CSS approach, and I'm going to close this issue. Thanks for suggesting the merge, though.

**Pull request closed without merging**
