### PR TITLE
Fix addRecords for case when oldRecords is empty

### PR DESCRIPTION
**Pull request by martynovs**

### CODE REVIEW

**Comment by fzaninotto** [comment]
When can `oldRecord` be empty? It's always called with `previousState`.

Can you explain the bug that it fixes?

**Comment by martynovs** [comment]
To try it out I've added CrudRoute to my app, with list page only and placeholder rest client.
```js
const restClient = jsonServerRestClient('http://jsonplaceholder.typicode.com');
```
```js
<CrudRoute key="posts" path="posts" list={PostList} />
```
```js
export default function PostsList(props) {
  return (
    <List {...props}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="title" />
        <TextField source="body" />
      </Datagrid>
    </List>
  );
}
```
It throws exception and shows nothing in list.

**Comment by fzaninotto** [comment]
I can't reproduce this bug, can you pack your test into one file and paste it here?

**Comment by martynovs** [comment]
I'll try to extract example tomorrow.

**Comment by fzaninotto** [comment]
Bump. Any news on this one?

**Comment by fzaninotto** [comment]
no news for more than a month, closing.

**Pull request closed without merging**
