### PR TITLE
Update SelectInput.js

### LINKED ISSUE #988: SelectInput with allowEmpty throws key-warning in React
Following the simple example of `SelectInput`: https://marmelab.com/admin-on-rest/Inputs.html#selectinput

When you add `allowEmpty` to SelectInput (which is require so that `ReferenceInput` works), react throws a warning: 
````
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `SelectInput`. See https://fb.me/react-warning-keys for more information.
    in MenuItem (created by SelectInput)
    in SelectInput (created by getContext(SelectInput))
    in getContext(SelectInput) (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by FormField)
    in FormField (created by SimpleForm)
    in div (created by SimpleForm)
    in div (created by SimpleForm)
    in form (created by SimpleForm)
    in SimpleForm (created by Form(SimpleForm))
    in Form(SimpleForm) (created by Connect(Form(SimpleForm)))
    in Connect(Form(SimpleForm)) (created by ReduxForm)
    in ReduxForm (created by Connect(ReduxForm))
    in Connect(ReduxForm) (created by Unknown)
    ...
````

### PR DESCRIPTION
**Pull request by fab1an**
Fix #988

### CODE REVIEW

**Comment by djhi** [comment]
I assume it did fix the problem ?

**Comment by fab1an** [comment]
I had no time to test it.

**Comment by djhi** [comment]
I just checked the tests output and I can confirm it did fix the issue :) Thanks!

**Comment by fab1an** [comment]
Thanks for testing it. Normally I adhere to the contribution guidelines of OSS projects, but in this case I'm in a bit of a special situation since I'm doing my development in Kotlin (with IntelliJ IDEA) and have no JavaScript environment (babel etc.) set up.

**Pull request merged**
