### PR TITLE
ImageField: allow to style the img tag

### PR DESCRIPTION
**Pull request by alanpoulain**
Useful for example if you want to change the size of the image:
```javascript
<ImageField key="imageLink" source="imageLink" elStyle={{image: {height: 40}}} />
``` 
If you are okay with this, I could add tests and/or docs.

### CODE REVIEW

**Comment by Simperfit** [comment]
ping @fzaninotto, this is blocking for us, could you please look at it if you have some time ?

**Comment by fzaninotto** [comment]
This is a new feature, so it should be PRed agains the `next` branch.

**Comment by alanpoulain** [comment]
@fzaninotto it's done.

**Comment by djhi** [comment]
Now that we use MaterialUI v1 and JSS on `next`, the `ImageField` can customized using:

```jsx
const MyImageField = withStyles({ image: { height: 40 })(ImageField);
MyImageField.defaultProps = ImageField.defaultProps;
```

**Comment by ricardovf** [comment]
This is how im doing:

```js
const styles = {
  image: { width: "50px" }
};

const AvatarField = withStyles(styles)(({ classes, ...props }) => (
  <ImageField classes={classes} source="frameUrl" label="Frame" {...props} />
));

<AvatarField />
```

**Pull request closed without merging**
