### PR TITLE
Action types prefix

### PR DESCRIPTION
**Pull request by kulakowka**
I added prefixes to the types of actions. This is useful to avoid conflicts with actions in the user's application.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Good idea. I'd prefer `AOR/` as prefix, could you update your PR? Also, tests fail.

**Comment by fzaninotto** [comment]
Will need rebase after #566

**Comment by fzaninotto** [comment]
please use capital letters, otherwise it's ugly

**Comment by fzaninotto** [comment]
bump

**Comment by ThieryMichel** [comment]
replaced by https://github.com/marmelab/admin-on-rest/pull/777

**Pull request closed without merging**
