### PR TITLE
Inital translation to postgrest REST

### PR DESCRIPTION
**Pull request by tomberek**
This is a starting point to provide a translation layer for the postgrest REST variant.

[1]: https://github.com/begriffs/postgrest

### CODE REVIEW

**Comment by tomberek** [comment]
It work somewhat well already for simple requests, though there is some duplication of requests made to the server.

- [ ] ensure all requests are properly translated
- [ ] ensure responses are translated
- [ ] add test cases

**Comment by fzaninotto** [comment]
Good start! Beware of mixed tabs and spaces, and `console.log()` remaining

**Comment by tomberek** [comment]
of course, this is work-in-progress, just wanted to allow others to contribute or code review in the meantime. I'll let you know when I'd like a merge.

**Comment by fzaninotto** [comment]
In fact, I'd prefer if you published this client on your own (see e.g [marmelab/aor-json-rest-client](https://github.com/marmelab/aor-json-rest-client). I'll point to it from the admin-on-rest documentation. 

That way, you can publish and maintain it at your own pace.

**Comment by tomberek** [comment]
okay,
https://github.com/tomberek/aor-postgrest-client

**Comment by fzaninotto** [comment]
Thanks, added to the readme in df217f16cede7478fbe4a489f0db3b34a2de3ff3

**Pull request closed without merging**
