### PR TITLE
[RFR] Use prettier for code formatting

### PR DESCRIPTION
**Pull request by fzaninotto**
Let's stop worrying about code formatting

### CODE REVIEW

**Comment by fzaninotto** [comment]
Wait, I'm missing some files

**Comment by fzaninotto** [comment]
And back to RFR

**Comment by djhi** [comment]
You could also use `husky` and `lint-staged` to automate `eslint --fix` whenever a file is committed. See https://github.com/marmelab/aor-dependent-input/ for an example (package.json).

**Comment by fzaninotto** [comment]
Linting the whole project is slow, I don't want to slow down the publication workflow for everybody with a precommit hook. Besides, I already added a `make prettier` which does a similar thing to `eslint --fix` on demand.

**Pull request merged**
