### PR TITLE
linkToRecord for ReferenceField

### PR DESCRIPTION
**Pull request by tomberek**
Revised PR from #262

### CODE REVIEW

**Comment by mantis** [comment]
I just hit this issue - so would be good to see a solution for this go in :)

I was wondering whether the final param should be a generic type so you could specify 'show' as text. That would allow someone to construct a path to /users/1/logonhistorygraph for instance - however i'm new to react so I realise that might not be the way things are generally done and I've just seen that is the opposite to what @fzaninotto said.

**Comment by fzaninotto** [comment]
I misunderstood you in #262. I thought you wanted to *remove* the link altogether, while in fact you want to *replace* it by a link to `Show`.

I think the best way to do that is to add a `addLink` prop, set to `true` by default. When set to false, `<ReferenceField>` would render the child component *without link*.

That way to link to show, you can set `addLink` to `false`, and, instead of a `<TextField>`, write your own `<Link>` tag as child. That way, whether you want to link to edit, show, or anything else, you can just write it in React.

**Comment by fzaninotto** [comment]
Oh, and this deserves a unit test

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by tomberek** [comment]
I've not worked on this for a month.

**Comment by fzaninotto** [comment]
Superseded by #490

**Pull request closed without merging**
