### PR TITLE
Update React (and react-dom) to 15.4.0 and react-tap-event-plugin to 2.0.1

### PR DESCRIPTION
**Pull request by petetnt**
... to fix React 15.4.0 compatibility).

This PR builds on the previous PR #153 which was reverted in #154 due to NPM warnings about missing peer deps (which I missed because my peer deps matched the ones that prompted the update in the first place). 

All tests pass, example works as it worked with the previous version.

Sorry about the hassle. cc @fzaninotto 

--- Old message:

[react-v15.4.0](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html) broke `react-tap-event-plugin@v1`, which got updated to 2.0.1. just now at https://github.com/zilverline/react-tap-event-plugin/pull/82. See the change set here: https://github.com/zilverline/react-tap-event-plugin/pull/82/files. It only changes the paths to `react-dom`.

Signed-off-by: petetnt <pete.a.nykanen@gmail.com>

### CODE REVIEW

**Comment by petetnt** [comment]
Argh, now the CI failed. Lemme see that one more time 😢

**Comment by fzaninotto** [comment]
I'll test locally and merge by hand if successful.

**Comment by fzaninotto** [comment]
I found a version conflict in material UI:

- React 0.15.4 is only compatible with [Material UI v0.16.3](https://github.com/callemall/material-ui/releases/tag/v0.16.3), so we need to upgrade material ui, too (currently fixed to v0.16.1)
- But Material UI v0.16.2 introduced a [regression](https://github.com/callemall/material-ui/issues/5590) which breaks the layout in the `<List>` component.

So we can't merge this PR until https://github.com/callemall/material-ui/issues/5590 is solved.

**Comment by petetnt** [comment]
Thanks @fzaninotto 👍

**Pull request merged**
