### PR TITLE
Expose polyglot instance

### PR DESCRIPTION
**Pull request by yshing**
Separate the creation of polyglot instance from TranslationProvider and make it expose at
admin-on-rest/i18n/polyglot.

### CODE REVIEW

**Comment by fzaninotto** [comment]
I don't understand why you'd need that, since the instance you expose is not configured. 

If you want to expose an instance and configure it afterwards and then reuse it again by requiring the original instance, it works by accident with AMD modules, but it is absolutely not future-proof (it won't work with ES6 modules).

Why don't you explain your requirement rather than just the solution you found?

**Comment by yshing** [comment]
You are right that it is meant to be loaded by 'require', but not an accident.

Webpack & Babel makes all your ES6 `import` a CommonJS `require`. It is not any day soon that you can use ES6 modules in browser without them. It is the nature of the tools you've chosen.

Using polyglot as a Singleton and expose it with admin-on-rest, allows AOR handle translation in a much more elegant way. And for users, it is also much easier and familiar to work with. 

Expose the instance without pre-configured is no more than trying to keep minimal changes to the existing behavior, personally I prefer to have it to pre-configured with the default languages is possible and use `polyglot.extend` in the TranslateProvider.


Why trade off the simplicity and usability against something not more than an illusion?

And why would you worries about the future that you can use JS modules without Webpack & Babel?

**Comment by fzaninotto** [comment]
I'd rather expose a `polyglot` prop on the `<Admin>` component to let developers inject their own instance of Polyglot instead of relying on a singleton.

**Comment by yshing** [comment]
Expose a `polyglot` and let user to inject a polyglot instance doesn't make much difference.
It would still need to have all those unnecessary wrapping of `translate(Component)` stuff.

And all the FiledTitles still silently pass `label` to polyglot.t, which is only because `ReferenceInput` sets `label` prop to `resources.${resource}.fields.${source}` if the `label` is `undefined` and end-up showing the end-user `resource.<sth>.fields.<sth>`.

It was `inflection.humanize(source)` in *0.7.X* and I thought that's pretty cool.

A whole lot of extra complexity was added into AOR to support the I18n in current React-ish favour.

When using an I18n instance, we can remove all those shadowed `translate` so that it would be easier for future maintenance and for newcomers  to join.
```js
transalte('sth', {_: 'fallback'}) // translate is (string, object) => string
export translate(sth) // translate is (React.Component)=>React.Component
```
The translation can then be used much precisely as it can be imported/required whenever its needed.

And users can use the I18n.t provided by admin-on-rest outside React. Hence use admin-on-rest to handle all the translations.

**Comment by fzaninotto** [comment]
Sorry, that's not the path we chose to follow. Architecture is all about compromises. The current implementation is a good balance between power and ease of use, what you propose isn't such a good balance IMO.

If you don't want to use `translate` in your own components, feel free not to.

**Pull request closed without merging**
