### PR TITLE
#7 Make it works with UUID

### PR DESCRIPTION
**Pull request by bjet007**
Hi Guy's.  I came across your project while I was looking for a quick way to build UI over my API.  Your project look great and we was easy to be configured for my API.  

Unfortunately, my API does use identifier that are not solely integer.  I'm not where near an UI expert, but here is my pull request to fix the bug.  From what I saw on my machine, it work, but maybe there is something missing.

Ben

### CODE REVIEW

**Comment by bjet007** [comment]
That's weird. Using the example provided in the project I can see them. 

The only thing that I did is installing the npm package and then running webpack before opening the index.html file in a browser.

Do you have any error that I could use to troubleshoot?

**Comment by jpetitcolas** [comment]
My bad: I forgot to mention I changed identifiers to strings in the `example/data.json`. All ids were `ABC-1`, `ABC-2`, and so on.

**Comment by bjet007** [comment]
Ok. I did change all post Id to string.  I can see post title in comment, but now sometime the fake rest server does not return result.  I don't know it the fake server always expect int, but it does seem to affect the component itself.

**Comment by bjet007** [comment]
BTW, my pull request was working before RecordForm was introduced, but with the current state of the master, i not able to load Create component having a ReferenceInput field.

I don't think it's related to my pull request, but I might spent some time restarting from a fresh checkout next week.  Are the example are still working with the current master?

**Comment by jpetitcolas** [comment]
Yes, we fixed several issues on master during last days, especially on filtering. It should be fine now.

**Comment by bjet007** [comment]
I've got the same issue with the example than with my code. 

I have create and issue for that: Create Component with ReferenceInput doesn't work anymore #58

**Comment by bjet007** [comment]
I found out why my pull request was not working with the example.  The FakeRest only accept numerical identifier when getting one item, but will return value when requesting a collection with a filter on id.  
Here is a screen shot of my javascript console.
admin-on-rest-console

Here is the regular expression that prevent non numerical id.
[https://github.com/marmelab/FakeRest/blob/master/src/Server.js#L277](url)

**Comment by bjet007** [comment]
Closing Pull Request, retrieving recent commit screw up my pull request

**Pull request closed without merging**
