### PR TITLE
feat: add ReferenceArrayField

### LINKED ISSUE #429: ReferenceManyField source=<Array>
I'm building a new REST API with many-to-many relationship. In this case it would be awesome if ReferenceManyField could work with list of ids in base object (using GET_MANY instead of GET_MANY_REFERENCE). Here is an example:

Get a list of posts with a list of their categories:
```
/posts
[
{
  "title": "My Awesome Post",
  "categories": [ 2, 3 ]
},
{
  "title": "My Second Post",
  "categories": [ 3, 4 ]
},
]
```
Then if we are in ListView we call GET_MANY for the distinct of all category's ids:
```
/categories?filter={ids:[2,3,4]}
[
{ id: 2, name: "Second Category"},
{ id: 3, name: "Third Category"},
{ id: 4, name: "Fourth Category"}
]
```
Finally we render them in our list view as simple as this:
```
<ReferenceManyField reference="categories" source="props.record.category">
  <SingleFieldList>
    <ChipField source="name" />
  </SingleFieldList>
</ReferenceManyField>
```

### PR DESCRIPTION
**Pull request by leesei**
Take 2, supersedes #536
Fixes #429

 Changes to be committed:
	modified:   docs/Fields.md
	modified:   example/app.js
	modified:   example/posts.js
	modified:   src/actions/referenceActions.js
	new file:   src/mui/field/ReferenceArrayField.js
	new file:   src/mui/field/ReferenceArrayField.spec.js
	modified:   src/mui/field/index.js
	modified:   src/reducer/references/oneToMany.js
	modified:   src/sideEffect/saga/referenceFetch.js

### CODE REVIEW

**Comment by leesei** [comment]
`CRUD_GET_ONE_REFERENCE` = many action taking single id debounced to single `GET_MANY`
`CRUD_GET_MANY_REFERENCE` = `GET_MANY_REFERENCE`
`CRUD_DEBOUNCED_GET_MANY` = many action taking id array debounced to single `GET_MANY`

Overloading of "Reference" is causing the issue here and masked the true purpose of debouncing actions in `referenceActions.js`.

**TODOS** (maybe in 1.0)
- [ ] rename `CRUD_GET_ONE_REFERENCE` to `CRUD_DEBOUNCED_GET_ONE`
- [ ] rename `referenceActions.js` to `debouncedActions.js`

**Comment by langhard** [comment]
Exactly what I need! I'm looking forward to a (fast) integration.

**Comment by sherryxiao1988** [comment]
I wonder what's the status of this PR? Really need to use this in my code. Let me know if there is anything I can help?

Thanks!

**Comment by nonotest** [comment]
same here, what is missing now?

**Comment by leesei** [comment]
Any update?
I won't be adding the [TODOS](#issuecomment-296931614) in this PR.

**Comment by fzaninotto** [comment]
I fixed a regression in `<ReferenceField>`, renamed the debounce action to `accumulate`, and made some adjustments to the documentation.

Overall, great PR, thanks a lot for your contribution!

**Pull request merged**
