### PR TITLE
[RFR] [Feature] allow passing record to Create

### PR DESCRIPTION
**Pull request by natrim**
because defaultValue on SimpleForm works only once and sometimes you need to prefill the form on create by dynamic data

### CODE REVIEW

**Comment by fzaninotto** [comment]
How would you use that to prefill the form based on dynamic data?

**Comment by natrim** [comment]
ie. i am getting partial object in `componentDidMount`
 which is asynchronously fetched from server

if you try to pass it as `defaultValue` to SimpleFom it will not get updated after fetch

so need some other way to prefill the record

**Comment by fzaninotto** [comment]
Can you share some code?

**Comment by natrim** [comment]
```
import { parse } from 'query-string';
import { withRouter } from 'react-router';
import { connect } from 'react-redux';
import { lifecycle, compose  } from 'recompose';
import { first } from 'lodash/array';
import { crudGetOne } from 'admin-on-rest/lib/actions';

const enhanceCreateForm = compose(
  withRouter,
  connect(
    (state, props) => {
      const params = parse(props.location.search);

      const defaultFormValues = {
        ...globalDefaultFormValues,
        type: params.type,
        contact_id: params.contact_id,
        scan_id: params.scan_id,
      };

      if (!params.scan_id) {
        return { defaultFormValues, params, data: null };
      }
      const scan_id = parseInt(params.scan_id, 10);
      if (
        !state.admin.resources.scan ||
        !state.admin.resources.scan.data[scan_id]
      ) {
        return { defaultFormValues, params, data: null };
      }

      const data = state.admin.resources.scan.data[scan_id];

      return {
        defaultFormValues,
        params,
        data: {
          type: 'pc',
          name: `${Array.isArray(data.machine_names)
            ? first(data.machine_names).value
            : `Scan id: ${data.id}`}`,
          ip: `${Array.isArray(data.ip_addresses)
            ? data.ip_addresses.map(v => v.value).join(',')
            : null}`,
          sn: data.motherboard_sn,
          licenses: Array.isArray(data.license_keys) ? data.license_keys : [],

          domain: `${Array.isArray(data.domain_names)
            ? first(data.domain_names).value
            : ''}`,

          // notes: JSON.stringify(data, null, ' '),
        },
      };
    },
    {
      getRow: crudGetOne,
    },
  ),
  lifecycle({
    componentDidMount() {
      if (parseInt(this.props.params.scan_id, 10) > 0) {
        this.props.getRow('scan', this.props.params.scan_id);
      }
    },
    componentWillReceiveProps(nextProps) {
      if (this.props.data !== nextProps.data) {
        this.setState({ record: nextProps.data });
      }
    },
  }),
);
```

**Comment by natrim** [comment]
rebased on the new next branch

**Comment by natrim** [comment]
@fzaninotto any other changes i should do to merge this?

**Comment by djhi** [comment]
Sorry @natrim, can you rebase again ?

**Comment by natrim** [comment]
@djhi tried clicking on resolve conflicts on github and it seems it worked .)

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
