### PR TITLE
[Wip]: Refactored crudFetch error handling

### PR DESCRIPTION
**Pull request by tkvw**
In response to a `fetch error` the `crudFetch` saga needs to know how the `auth` saga handled the error. For this I moved the `FETCH_ERROR` event on top and wait for a reaction of the `auth` saga what to do. If the FETCH_ERROR is handled, the user is redirected to `/login` so the `crudResponse` does not need to handle the `FAILURE` event. 

This ensures that the behaviour of https://github.com/marmelab/admin-on-rest/pull/1339 is fixed.

### CODE REVIEW

**Comment by tkvw** [comment]
Superseded by https://github.com/marmelab/admin-on-rest/pull/1354

**Comment by tkvw** [comment]
Not superseded by #1354, removed it from that PR to keep it minimal.

**Comment by djhi** [comment]
Still in `WIP`. What's missing for RFR ?

**Comment by tkvw** [comment]
Because of the proposed changes to server validation, I moved this code there. 
@see: https://github.com/marmelab/admin-on-rest/pull/1354/commits/934f42cb80b86c0e556efbe4cd4bd404ceaa92d9

**Comment by djhi** [comment]
So should this be closed ?

**Comment by tkvw** [comment]
Superseded by https://github.com/marmelab/admin-on-rest/pull/1354

**Pull request closed without merging**
