### PR TITLE
[RFR] Display command list for mobile

### PR DESCRIPTION
**Pull request by alexisjanvier**
capture d ecran de 2018-02-19 10-50-35
capture d ecran de 2018-02-19 10-52-16

### CODE REVIEW

**Comment by fzaninotto** [comment]
Great! One suggestion: could you move the edit button to the top left? This would save some vertical space by making each card smaller in size.

**Comment by fzaninotto** [comment]
Also, please align title and content on the same vertical line

image

**Comment by djhi** [comment]
I think quantity should be removed too as an order might have multiple products and a quantity for each

**Comment by alexisjanvier** [comment]
@fzaninotto @djhi  review applied

capture d ecran de 2018-02-19 11-51-40

And by consistency

capture d ecran de 2018-02-19 11-47-37

**Pull request merged**
