### PR TITLE
Pass options to BooleanInput for Toggle

### PR DESCRIPTION
**Pull request by iamsimakov**
I need to set right position for label for BooleanInput and find that there is not properties which responsible for it. I'm sorry if I did not fully understand in this problem. I think that this commit will be useful. what do you think about it?

### CODE REVIEW

**Comment by fzaninotto** [comment]
Great! I just need two small changes:

- Please mention the `options` option in the component documentation
- As this is a new feature, please pull against the `next` branch instead of `master`

**Comment by iamsimakov** [comment]
Very thank you! I did this fixes to my branch `iamsimakov:next`.
Will be normal if I open new PR from my `next` branch?  If yes then please close this PR and I will open new from `iamsimakov:next`.

**Comment by djhi** [comment]
I think you messed up with a rebase here. Can you rebase your branch from our `next` branch ?

**Comment by djhi** [comment]
If too difficult, please close this PR and open a new one

**Pull request closed without merging**
