### PR TITLE
[RFR] Datagrid header icons

### PR DESCRIPTION
**Pull request by pimschaaf**
A more tolerant check for label values could allow for the use of icons in Datagrid headers. By allowing `PropTypes.element` in addition to `PropTypes.string` as field label, icons can be displayed as shown [here](http://i.imgur.com/lQR9LE0.png).

With this change, translation of field labels that are React Elements will not be performed in FieldTitle.js (strings will be translated).

This is my first PR to this repo. I'm open to suggestions :)

### CODE REVIEW

**Comment by djhi** [comment]
Thx! Can you add something in the [documentation](https://marmelab.com/admin-on-rest/Fields.html) about this ?

With a link to the [translating your own components](https://marmelab.com/admin-on-rest/Translation.html#translating-your-own-components) section to explain how to get translation for inner labels too.

**Comment by fzaninotto** [comment]
As far as I understand it, this breaks datagrid header translation... so I'm -1 on merging this for now.

**Comment by pimschaaf** [comment]
@djhi thanks for your suggestion. I can do that.

@fzaninotto:
I'm not sure if I understand you correctly. Datagrid header translation for strings as labels is preserved as shown in the linked screenshot. Is there anything that I am missing?

Translation for React Elements as labels is not supported. Would that be a requirement?

**Comment by fzaninotto** [comment]
> Translation for React Elements as labels is not supported. Would that be a requirement?

Yes, indeed.

**Comment by pimschaaf** [comment]
@fzaninotto Would there be a way to restrict the test for Proptypes.element further, to only match elements that are (SVG) icons? 

I think limiting the scope as such would make more sense.

**Comment by fzaninotto** [comment]
Bad rebase, please push only your changes to this branch

**Comment by fzaninotto** [comment]
Bump, I will close this PR soon if you can't rebase and finish it.

**Comment by pimschaaf** [comment]
Please close it. I cannot finish it any time soon, sorry.

Op 25 jul. 2017 09:11 schreef "Francois Zaninotto" <notifications@github.com

**Pull request closed without merging**
