### PR TITLE
[RFR] Documentation - Examples section

### PR DESCRIPTION
**Pull request by djhi**
Add an `Examples` section to the documentation with a first example showing how to add a Create button linked to a ReferenceManyField

### CODE REVIEW

**Comment by fzaninotto** [comment]
IMO, There are enough sections in the documentation already. Use either the FAQ, or add a section in the `CreateEdit` chapter.

**Comment by djhi** [comment]
I disagree. IMI, FAQ should be for troubleshooting. Besides, I really think we should have a dedicated section for examples and, eventually, add links to it inside pure documentation sections such as `CreateEdit`.

**Comment by fzaninotto** [comment]
Better : implement this in one of the existing examples (e.g. create comment for post), and add a link to the code in CreateEdit.

**Comment by djhi** [comment]
My idea for the examples was to always start from the posts/comment base and show a specific recipe in addition.

But ok. I fear that we might end up with a very complicated simple example though, where someone won't be able to find answer to a simple question.

**Pull request closed without merging**
