### PR TITLE
Fix translation page link

### PR DESCRIPTION
**Pull request by Phocea**

### CODE REVIEW

**Comment by djhi** [comment]
Thanks!

**Comment by Kmaschta** [comment]
We need the .html on the live documentation: https://marmelab.com/admin-on-rest/Ecosystem.html

@djhi @Phocea

**Comment by Kmaschta** [comment]
It seems that Jekyll do the job ! Don't mind my comment.

**Comment by Phocea** [comment]
@Kmaschta Yes i was checking on this yesterday, since there is quiet a few, but Jekyll is handling it. i will fix the others I spotted

**Pull request merged**
