### PR TITLE
[DOC] Add material-ui dependence

### PR DESCRIPTION
**Pull request by kpitn**

### CODE REVIEW

**Comment by fzaninotto** [comment]
It's only a problem if you use npm 2 isn't it?

**Comment by kpitn** [comment]
I don't know if it's related, but I'm usingnpm 2.15.8

**Comment by jpetitcolas** [comment]
Which version are you using? Because `material-ui` is already listed as dependencies: https://github.com/marmelab/admin-on-rest/blob/master/package.json#L57

**Comment by fzaninotto** [comment]
But the tutorial only asks to install admin-on-rest. With npm 2, admin-on-rest's dependencies (including `material-ui`) are under `node_modules/admin-on-rest/node_modules` and can't be found by a simple `import`.

Npm 2 is outdated, and we don't want to spend time supporting it. Instead of making the documentation harder to follow, I suggest that we add node 5 (with npm 3) as required dependency of admin-on-rest.

**Pull request closed without merging**
