### PR TITLE
Add greek translation

### PR DESCRIPTION
**Pull request by zifnab87**

### CODE REVIEW

**Comment by djhi** [comment]
Thanks!

**Comment by afilp** [comment]
Thanks too!

**Comment by afilp** [comment]
@djhi I wonder, how can someone change these (map them) to another language? I assume these are populated from the db column names and tables, is there a way to override them and show greek titles?

image

Thanks!

**Comment by fzaninotto** [comment]
@afilp https://marmelab.com/admin-on-rest/Translation.html#translating-resource-and-field-names

**Pull request merged**
