### PR TITLE
Prefix flex-box containers

### PR DESCRIPTION
**Pull request by yshing**
Prefix flex-box containers ....

### CODE REVIEW

**Comment by fzaninotto** [comment]
The added dependency (react-prefixer) on prefixes 'display' and 'transition', and has only 5 stars. I'd be more comfortable if you added the prefixed CSS properties directly in the style object and removed the dependency.

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by yshing** [comment]
Not yet found a perfect solution for using flex with inline style property.. 
Found this package, but Github Repo is GONE.
https://www.npmjs.com/package/react-flex

**Comment by yshing** [comment]
@fzaninotto 
Maybe we can just rely material-ui to do the auto-prefixing?

**Comment by yshing** [comment]
And material-ui@0.16.7 seems working perfectly for both older and newer versions of Firefox.

https://github.com/callemall/material-ui/pull/5931

**Comment by fzaninotto** [comment]
Excellent! Since this adds a new dependency, can you PR against the `next` branch (due to be released next week) instead of the `master` branch?

**Comment by yshing** [comment]
Sure, created a PR against the next branch #296

**Pull request closed without merging**
