### PR TITLE
Make the FileInputPreview themeable

### PR DESCRIPTION
**Pull request by natrim**
aka the remove icon had hardcoded color

### CODE REVIEW

**Comment by natrim** [comment]
ugh, no idea why it fails...

**Comment by natrim** [comment]
i added it to the `FileInputPreview.spec.js`, but have no idea how to get it to the `FileInput` and `ImageInput` tests

**Comment by natrim** [comment]
well i should probably have made only an issue and not trying pull req. as i have no idea how to fix the tests

**Comment by djhi** [comment]
Superseded by #1084

**Pull request closed without merging**
