### PR TITLE
[RFR] Humanize camel case sources

### LINKED ISSUE #994: camelCase Field source naming doesn't produce readable labels like snake_case does
for example `is_resolved` in field source creates `IS RESOLVED`
while `isResolved` creates `ISRESOLVED` 

`<BooleanField source="isResolved" />`
vs
`<BooleanField source="is_resolved" />`

any plans for supporting camelCase and PascalCase?

Thanks!

### PR DESCRIPTION
**Pull request by Kmaschta**
Fixes #994

### CODE REVIEW

**Comment by alexisjanvier** [comment]
@Kmaschta need a small fix for linter

**Comment by Kmaschta** [comment]
Fixed!

**Comment by djhi** [comment]
Don't merge please

**Comment by djhi** [comment]
Needs rebase :)

**Comment by Kmaschta** [comment]
Rebased!

**Pull request merged**
