### PR TITLE
[RFR] Allow to override SimpleShowLayout container styles

### PR DESCRIPTION
**Pull request by djhi**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Sorry, but this needs to be PRed against `next`

**Comment by fzaninotto** [comment]
Also, could you document the new option?

**Comment by djhi** [comment]
I can rebase against next. However, the documentation for `Show` and `ShowLayout` has only been done in `master`

**Comment by fzaninotto** [comment]
I've just merged `master` into `next`

**Pull request merged**
