### PR TITLE
Make the FilterForm themeable

### PR DESCRIPTION
**Pull request by natrim**
aka the delete filter button had hardcoded color

### CODE REVIEW

**Comment by natrim** [comment]
ugh, no idea why it fails...

**Comment by natrim** [comment]
reason this one got closed?

**Comment by djhi** [comment]
Sorry about that, I thought it was a duplicate of #986

**Comment by natrim** [comment]
well i should probably have made only an issue and not trying pull req. as i have no idea how to fix the tests

**Comment by fzaninotto** [comment]
Try to run the unit tests on your machine and you'll see: you've added a new required prop to the component, but the unit tests don't provide it.

**Comment by djhi** [comment]
You can refer to other themable components tests for inspiration: 
- https://github.com/marmelab/admin-on-rest/blob/f554814aed664211b8d337545e11024f41ba5323/src/mui/form/TabbedForm.spec.js
- https://github.com/marmelab/admin-on-rest/blob/0622e8c8c54d128dabc49518e0ba7bf6d3cca62b/src/mui/input/CheckboxGroupInput.spec.js

**Comment by natrim** [comment]
but these test are for directly the component that uses muiTheme
the direct test for FilterForm works
it's the one for Filter that fails and i have no idea how to pass it
i even tried wrapping it with MuiThemeProvider and it still failed

**Comment by djhi** [comment]
Superseded by #1083

**Pull request closed without merging**
