### PR TITLE
[RFR] Fix custom title in view and custom label in resource

### PR DESCRIPTION
**Pull request by fzaninotto**
Supersedes #314

### CODE REVIEW

**Comment by yshing** [comment]
Hi @fzaninotto, 
This is still silently passing every custom labels towards the new translation function introduced in v0.8.0.
However I think is more important to render custom labels as it is, so users is not bounded to polygot.js.

I've updated desired changes to yshing@c12f3495ebf5eb571616626c42db034889980892

And desired update on the way of using translate:  yshing@8d1927f96ddd1318beba9f22b77eee5cf9779d54

By doing so, all custom label should remain intact, and the developer should be responsible of translating the labels before passing it to the `label` property using whatever I18n implementation or the one comes with AOR. 

And the `translate` function can be passed as props to users' custom CRUD model, so that they can do sth like:
```js
import I18n from 'i18n'
import {Create, SimpleForm, TextInput} from 'admin-on-rest/mui'
export const ProstCreate ({ ...props }) => {
    <Create {...props}>
        <SimpleForm>
            <TextInput source="title" label={props.translate('foo.bar')} />
            <TextInput source="title1" label={I18n.t('foo.bar')} />
            <TextInput source="title2"/>
        </SimpleForm>
    </Create>
}
```

**Comment by fzaninotto** [comment]
> This is still silently passing every custom labels towards the new translation function introduced in v0.8.0.

That's on purpose.

> However I think is more important to render custom labels as it is, so users is not bounded to polygot.js.

I disagree. If you don't want your code to go silently through polyglot (and I don't understand why), use your own components. 

> the developer should be responsible of translating the labels before passing it to the `label` property 

That's exactly what I want to avoid, because this brings a lot of confusion, and makes development slower. With the current design, any label passed to an admin-on-rest component gets translated by default ; developers only need to use `translate` for their own components.

**Comment by yshing** [comment]
What I really concern is that, there is now no way to set those `label` and `title` with confidence when everything is passed to polygot.js.

And I think AOR is common to be used with other I18n library as the new translation functionality is just released, in this case everything passed to `title` and `label` is already translated. 

I really wish the translation features could be introduced in a opt-in style and allow user to use their own I18n implementation with AOR.

**Comment by fzaninotto** [comment]
>  there is now no way to set those label and title with confidence when everything is passed to polygot.js.

Be confident: it's passed to polyglot, but if you provide no translation, polyglot will return it as is. It may call the NSA in the process, but you'll never know.

> I think AOR is common to be used with other I18n library

I've never heard about that. For projects using this approach: it's not supported.

> I really wish the translation features could be introduced in a opt-in style

It is opt-in: if you don't want to use `locale` and `messages`, pass labels in your language, and they will be displayed

> allow user to use their own I18n implementation with AOR.

No, as well as not offering to use MobX instead of Redux, or Inferno instead of React, etc. Admin-on-rest is an opinionated library, building on top of popular projects. That's what makes it so powerful and easy to use, that's what makes it easy to reason with, that's what makes it fast.

**Pull request merged**
